// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as WailsService from "./wailsservice.js";
export {
    WailsService
};

export type {
    Agent,
    ConflictResolution,
    ConflictResolutionStatus,
    ConflictSelection,
    ConflictSummary,
    CustomResourceInput,
    InstallOperation,
    InstallPlan,
    Progress,
    ResetPreview,
    ResourceCategory,
    ResourceIssue,
    ResourcePreview,
    SettingsInput,
    Snapshot,
    SyncDiagnostic,
    SyncFixStep,
    SyncNoticeIssue,
    SyncNotices
} from "./models.js";
