// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Agent is one provider shown in the desktop application.
 */
export interface Agent {
    "name": string;
    "enabled": boolean;
    "exclude": string[] | null;
    "resources": ResourceCategory[] | null;
}

export interface ConflictResolution {
    "id": string;
    "choice": string;
    "content"?: string;
}

export interface ConflictResolutionStatus {
    "id": string;
    "status": string;
    "selected": number;
    "error"?: string;
}

export interface ConflictSelection {
    "id": string;
    "revision": string;
    "choice": string;
    "content"?: string;
}

export interface ConflictSummary {
    "id": string;
    "revision": string;
    "resourceKey": string;
    "path": string;
    "createdAt": string;
}

export interface CustomResourceInput {
    "id": string;
    "category": string;
    "paths": { [_ in string]?: string } | null;
    "targets": { [_ in string]?: string } | null;
    "include": string[] | null;
    "exclude": string[] | null;
    "strategy": string;
}

export interface InstallOperation {
    "id": string;
    "adapter": string;
    "source": string;
    "kind": string;
    "executable": string;
    "args": string[] | null;
    "workingDir": string;
    "error"?: string;
}

export interface InstallPlan {
    "id": string;
    "approved": boolean;
    "operations": InstallOperation[] | null;
}

export interface Progress {
    "revision"?: number;
    "stage": string;
    "label": string;
    "percentage": number;
    "completedActions": number;
    "totalActions": number;
    "blockedFiles": number;
    "pushed": boolean;
    "restored": number;
    "reinstalled": number;
    "skipped": number;
    "conflicts": number;
    "pendingInstalls": number;
    "needsAttention": boolean;
}

export interface ResetPreview {
    "repoPath": string;
}

export interface ResourceCategory {
    "provider": string;
    "id": string;
    "category": string;
    "enabled": boolean;
    "supported": boolean;
    "source": string;
    "target": string;
    "fileCount": number;
    "bytes": number;
    "excludedFiles": number;
    "excludedBytes": number;
    "status": string;
    "reason"?: string;
}

export interface ResourceIssue {
    "resourceKey": string;
    "path": string;
    "code": string;
    "message": string;
    "bytes": number;
}

export interface ResourcePreview {
    "generatedAt": string;
    "resources": ResourceCategory[] | null;
    "files": number;
    "bytes": number;
    "excludedFiles": number;
    "excludedBytes": number;
    "issues": ResourceIssue[] | null;
}

/**
 * SettingsInput contains editable desktop settings.
 */
export interface SettingsInput {
    "repositoryUrl": string;
    "repositoryDir"?: string;
    "repoPathMode"?: string;
    "firstSyncStrategy"?: string;
    "firstSyncChoiceRequired"?: boolean;
    "intervalMinutes": number;
    "trashGraceDays": number;
    "agents": { [_ in string]?: boolean } | null;
    "categories": { [_ in string]?: { [_ in string]?: boolean } | null } | null;
    "customResources": CustomResourceInput[] | null;
}

/**
 * Snapshot is the current desktop-visible sync state.
 */
export interface Snapshot {
    "revision"?: number;
    "configured": boolean;
    "state": string;
    "repositoryUrl": string;
    "platform": string;
    "intervalMinutes": number;
    "trashGraceDays": number;
    "agents": Agent[] | null;
    "lastSync": string;
    "nextSync": string;
    "pendingActions": number;
    "blockedFiles": number;
    "lastError": string;
    "repoPath": string;
    "firstSyncRequired": boolean;
    "syncDiagnostic"?: SyncDiagnostic | null;
    "syncNotices"?: SyncNotices | null;
    "progress": Progress;
    "preview": ResourcePreview;
    "customResources": CustomResourceInput[] | null;
    "pendingInstallPlan"?: InstallPlan | null;
    "conflicts": ConflictSummary[] | null;
    "conflictResolution"?: ConflictResolutionStatus | null;
}

export interface SyncDiagnostic {
    "code": string;
    "summary": string;
    "repoPath": string;
    "steps": SyncFixStep[] | null;
}

export interface SyncFixStep {
    "title": string;
    "command": string;
    "warning"?: string;
}

export interface SyncNoticeIssue {
    "resourceKey": string;
    "path": string;
    "code": string;
    "message": string;
    "bytes": number;
    "kind": string;
    "reviewable": boolean;
}

export interface SyncNotices {
    "version": number;
    "fingerprint": string;
    "finishedAt": string;
    "skipped": number;
    "blocked": number;
    "detailsAvailable": boolean;
    "reviewed": boolean;
    "issues": SyncNoticeIssue[] | null;
}
