// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WailsService exposes the UI-safe desktop API to generated Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as onboarding$0 from "../onboarding/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "../updater/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AcknowledgeSyncNotices(fingerprint: string): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(992847316, fingerprint);
}

export function ApproveInstallPlan(id: string): $CancellablePromise<void> {
    return $Call.ByID(1695820935, id);
}

export function CancelOnboarding(): $CancellablePromise<void> {
    return $Call.ByID(3153265431);
}

export function CheckForUpdates(): $CancellablePromise<updater$0.Status> {
    return $Call.ByID(749283935);
}

export function CompleteOnboarding(enabled: { [_ in string]?: boolean } | null): $CancellablePromise<void> {
    return $Call.ByID(367143950, enabled);
}

export function NeedsOnboarding(): $CancellablePromise<boolean> {
    return $Call.ByID(2131389736);
}

export function OnboardingState(): $CancellablePromise<onboarding$0.State> {
    return $Call.ByID(386154610);
}

export function Pause(): $CancellablePromise<void> {
    return $Call.ByID(2754654834);
}

export function PreviewCustomResource(input: $models.CustomResourceInput): $CancellablePromise<$models.ResourcePreview> {
    return $Call.ByID(3594254427, input);
}

export function QueueConflictBatch(selections: $models.ConflictSelection[] | null): $CancellablePromise<void> {
    return $Call.ByID(2823790371, selections);
}

export function ResetLocalSetup(confirmation: string, repoPath: string): $CancellablePromise<void> {
    return $Call.ByID(3414701819, confirmation, repoPath);
}

export function ResetPreview(): $CancellablePromise<$models.ResetPreview> {
    return $Call.ByID(2755306697);
}

export function ResolveConflict(input: $models.ConflictResolution): $CancellablePromise<void> {
    return $Call.ByID(3976618230, input);
}

export function ResourcePreview(): $CancellablePromise<$models.ResourcePreview> {
    return $Call.ByID(2524841168);
}

export function RestartToUpdate(): $CancellablePromise<void> {
    return $Call.ByID(4019363215);
}

export function Resume(): $CancellablePromise<void> {
    return $Call.ByID(209216979);
}

export function RetryConflictBatch(id: string): $CancellablePromise<void> {
    return $Call.ByID(2270072392, id);
}

export function RetryInstallPlan(id: string): $CancellablePromise<void> {
    return $Call.ByID(829636702, id);
}

export function ReturnToRepository(): $CancellablePromise<onboarding$0.State> {
    return $Call.ByID(275441407);
}

export function SaveSettings(input: $models.SettingsInput): $CancellablePromise<void> {
    return $Call.ByID(3950727776, input);
}

export function SetAutomaticUpdates(enabled: boolean): $CancellablePromise<updater$0.Status> {
    return $Call.ByID(311923335, enabled);
}

export function SetRepository(raw: string): $CancellablePromise<void> {
    return $Call.ByID(566394724, raw);
}

export function SetStartAtLogin(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3530873694, enabled);
}

export function Snapshot(): $CancellablePromise<$models.Snapshot> {
    return $Call.ByID(3816368756);
}

export function StartAtLogin(): $CancellablePromise<boolean> {
    return $Call.ByID(2736855374);
}

export function StartGitHubLogin(): $CancellablePromise<onboarding$0.State> {
    return $Call.ByID(2111959360);
}

export function TriggerSync(): $CancellablePromise<void> {
    return $Call.ByID(1437252511);
}

export function UpdateStatus(): $CancellablePromise<updater$0.Status> {
    return $Call.ByID(1632584675);
}

export function VerifySSH(): $CancellablePromise<onboarding$0.State> {
    return $Call.ByID(1157161353);
}

export function WaitGitHubLogin(): $CancellablePromise<onboarding$0.State> {
    return $Call.ByID(562452083);
}
